website/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

   ]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    # link for logo

    #STRING REPRESENTATION
    def __str__(self):
        return self.artist+'-'+self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)


    #STRING REPRESENTATION
    def __str__(self):
        return self.song_title

website/music/views.py
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Album,Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
         #getting value of selected song
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {'album': album, 'error_message': "No songs selected", })
    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

website/music/templates/music/detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<img src="{{ album.album_logo }}" height="275px" width="275px">
<h1>{{ album.album_title }}</h1>
<h4>{{ album.artist }} - {{ album.genre }} </h4>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favourite' album.id %}" method="POST">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">

        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {{ song.is_favourite }}
            {% if song.is_favourite %}
                <img src="http://i.imgur.com/b9b13Rd.png">
            {% endif %}
        </label>
        <br>
    {% endfor %}
    <input type="submit" value="Add Favourite">
</form>






</body>
</html>

website/music/templates/music/index.html
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <nav class="navbar navbar-default">

        <div class="container-fluid">
            <div class="navbar-header">
                 <a href="{% url 'music:index' %}" class="navbar-brand">Django Musics</a>
            </div>
        </div>
    </nav>
  {% if all_albums %}
    <h3>Your Albums</h3>
    <ul>
    {% for album in all_albums %}
    <li><a href="{{ album.id }}">{{ album.album_title }}</a> </li>
    {% endfor %}
        </ul>
  {% else %}
    <h3>You got No Albums Dude</h3>
  {% endif %}